FROM python:3.8-slim
WORKDIR /flask

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt ./
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . ./

ENV SECRET_KEY="my_secret_key"
CMD ["gunicorn", "--bind=0.0.0.0:80", "start:app"]